version: '2'
services:
    rsslive-app:
        image: rsslive
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mariadb://rsslive-mariadb:3306/rsslive
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=rsslive-elasticsearch:9300
        ports:
            - 8080:8080
    rsslive-mariadb:
        extends:
            file: mariadb.yml
            service: rsslive-mariadb
    rsslive-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: rsslive-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
